### ISSUE TITLE
Stone & Cobblestone BUG!

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#10] opened 2016-09-20 20:50 UTC
Mining stone gives you stone and not cobble stone (looks like there is no way to get cobble stone)
so you can not craft an stone pickaxe

**Comment by Codepixl** [comment] 2016-09-21 01:04
This is not a bug, I have just not implemented Cobblestone yet. It will be in the next release.

**Closed by Codepixl** 2016-09-21 01:04 UTC
